### ISSUE TITLE
ADD README

### ISSUE THREAD

**Issue by aryanmonger20** [aryanmonger20/WeatherApp#2]

**Comment by r4pt0s** [comment]
Hi,
What kind of Readme are you looking for?
What are the parts which the Readme should contain?

I would be happy to help you out.

**Comment by aryanmonger20** [comment]
@r4pt0s Just a basic one giving a brief idea about it.

**Comment by r4pt0s** [comment]
With how to fork an how to contribute or do you want to leave that off?

**Comment by aryanmonger20** [comment]
@r4pt0s  yeah you can include those too.

**Comment by r4pt0s** [comment]
Great.
I think I already have a good boilerplate which I can use in your case as well.
You can assign the task to me.

Happy coding
